### ISSUE TITLE
词库不全导致无法准确终止

### ISSUE THREAD

**Issue by KKKangKaiKK** [callmebg/idioms_follow#1]
例如唯唯否否，实际上可以接否终斯泰

**Comment by callmebg** [comment]
感谢🙏您的反馈。个人认为这是由于腾讯方面的词库不大准确，唯唯否否最后一个字应该是fou。还有一些软件无法接龙，但是qq红包可以的词，在下面知乎文章的评论区可以找到
https://zhuanlan.zhihu.com/p/78014601

万一以后我记起来了，我就改一改，嘤嘤嘤

---原始邮件---
发件人: "LuoFan"<notifications@github.com>
发送时间: 2019年8月26日(星期一) 下午5:21
收件人: "callmebg/idioms_follow"<idioms_follow@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [callmebg/idioms_follow] 词库不全导致无法准确终止 (#1)



例如唯唯否否，实际上可以接否终斯泰

**Comment by KKKangKaiKK** [comment]
> 感谢🙏您的反馈。个人认为这是由于腾讯方面的词库不大准确，唯唯否否最后一个字应该是fou。还有一些软件无法接龙，但是qq红包可以的词，在下面知乎文章的评论区可以找到 https://zhuanlan.zhihu.com/p/78014601 万一以后我记起来了，我就改一改，嘤嘤嘤
> […](#)

OK
